### ISSUE TITLE
[DatingApp version 1.0 ] The application crashes when I click ok icon or tick icon

### ISSUE THREAD

**Issue by friendsmobile** [quintuslabs/DatingApp#1]
<table class="">
 <tbody>
  <tr>
   <th scope="row">-----------------------------</a>Project Information-------------------------------------</th>
   <td>.</td>
  </tr>
  <tr>

<table class="properties">
 <tbody>
  <tr>
   <th scope="row">Project Respotry</a></th>
   <td>https://github.com/quintuslabs/DatingApp</td>
  </tr>
  <tr>
   <th scope="row">Project Name:</th>
   <td> DatingApp</a>.</td>
  </tr>
  <tr>
   <th scope="row">My Github Account</th>
   <td>  https://github.com/friendsmobile.</td>
  </tr>
  <tr>
   <th scope="row"> APK Downlod </th>
   <td> <h1><h6>https://github.com/quintuslabs/DatingApp/blob/master/lovedating1.0.apk.</td>
  </tr
  <tr>
   <th 
  <td> <
  </tr>
  <tr>

 </tbody>
</table>
</stope>
</end>

#### Expected behavior 

After opening the application, when I click on the information by clicking on the info and from where I click on ok icon, the application crashes.

#### Actual behavior
The application crashes when I click ok icon or tick icon

#### How to reproduce

* open the [application](https://github.com/quintuslabs/DatingApp/blob/master/lovedating1.0.apk)
* click on the profile info icon 
* After opening the info icon click OK icon
* Note the Error

* Browser/App version: 1.0
* Operating system: 6.0

#### Recording Of The Bug

![20190702_103452](https://user-images.githubusercontent.com/51118734/60485501-0f552380-9c52-11e9-8945-cd052f5fe147.gif)

#### Logcat

<pre><code>D/AndroidRuntime(11176): Shutting down VM

E/AndroidRuntime(11176): FATAL EXCEPTION: main

E/AndroidRuntime(11176): Process: com.quintus.labs.datingapp, PID: 11176

E/AndroidRuntime(11176): java.lang.IllegalStateException: Could not find method LikeBtn(View) in a parent or ancestor Context for android:onClick attribute defined on view class android.support.v7.widget.AppCompatImageButton with id 'likebtn'

E/AndroidRuntime(11176): 	at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.resolveMethod(AppCompatViewInflater.java:424)

E/AndroidRuntime(11176): 	at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:381)

E/AndroidRuntime(11176): 	at android.view.View.performClick(View.java:5076)

E/AndroidRuntime(11176): 	at android.view.View$PerformClick.run(View.java:20279)

E/AndroidRuntime(11176): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(11176): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(11176): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(11176): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(11176): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(11176): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(11176): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(11176): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
</code></pre>

**Comment by quintuslabs** [comment]
Let me check i will resolve that error. But this is not an complete application. this is a template of application

**Comment by friendsmobile** [comment]
thank you,I am waiting for your response 

and I know this is not a complete app

**Comment by quintuslabs** [comment]
[DatingApp version 1.0 ] The application crashes when I click ok icon or tick icon #1 issue resolved plaese pull or latest release source code . If issue is resolved please close  Issue.
Thank u.

**Comment by friendsmobile** [comment]
both bugs are still available

**Comment by friendsmobile** [comment]
both bugs are still available please recheck the issue

**Comment by quintuslabs** [comment]
DatingApp/app/src/main/java/com/quintus/labs/datingapp/Main/ProfileCheckinMain.java
Pleasd check this file and replace with your code. It will resolved your code
https://github.com/quintuslabs/DatingApp/blob/master/app/src/main/java/com/quintus/labs/datingapp/Main/ProfileCheckinMain.java

**Comment by quintuslabs** [comment]
https://github.com/quintuslabs/DatingApp/blob/master/app/src/main/java/com/quintus/labs/datingapp/Main/ProfileCheckinMain.java
Follow this link

**Comment by friendsmobile** [comment]
i  check just wait a minute

**Comment by friendsmobile** [comment]
still bug avaliable and i cannot find any  update file please release new version and update the code and then send me link

**Comment by quintuslabs** [comment]
Please check that link that i have provided u in the comment

https://github.com/quintuslabs/DatingApp/blob/master/app/src/main/java/com/quintus/labs/datingapp/Main/ProfileCheckinMain.java
Copy the code and paste in ur file it will work

**Comment by friendsmobile** [comment]
i try many time nut i cannot find file where i can put the code 

acutally i have zero programing knowledge

**Comment by santoshnet** [comment]
Go to my repository and check the file structure and also in that link ther
is file structure
src/main/java/com/quintus/labs/datingapp/Main/ProfileCheckinMain.java

**Comment by friendsmobile** [comment]
The codes appear when I open the link and I do not know what to do with this code

**Comment by friendsmobile** [comment]
please give me apk updates link  there I download it and check it out

**Comment by quintuslabs** [comment]
https://github.com/quintuslabs/DatingApp/blob/master/lovedating1.1.apk

check updated apk

**Comment by friendsmobile** [comment]
ok wait

**Comment by friendsmobile** [comment]
@quintuslabs  thanks you the bug has been solved now  check my  GIF video 

![20190703_090558](https://user-images.githubusercontent.com/51118734/60562674-548a5b80-9d0d-11e9-853f-76f69f7e8257.gif)

**Comment by quintuslabs** [comment]
[DatingApp version 1.0 ] The application crashes when I click ok icon or tick icon #1 Issue resolved
