### ISSUE TITLE
[DatingApp version 1.0 ] The application crashes when I click the close icon 

### ISSUE THREAD

**Issue by friendsmobile** [quintuslabs/DatingApp#2]
<table class="">
 <tbody>
  <tr>
   <th scope="row">-----------------------------</a>Project Information-------------------------------------</th>
   <td>.</td>
  </tr>
  <tr>

<table class="properties">
 <tbody>
  <tr>
   <th scope="row">Project Respotry</a></th>
   <td>https://github.com/quintuslabs/DatingApp</td>
  </tr>
  <tr>
   <th scope="row">Project Name:</th>
   <td> DatingApp</a>.</td>
  </tr>
  <tr>
   <th scope="row">My Github Account</th>
   <td>  https://github.com/friendsmobile.</td>
  </tr>
  <tr>
   <th scope="row"> APK Downlod </th>
   <td> <h1><h6>https://github.com/quintuslabs/DatingApp/blob/master/lovedating1.0.apk.</td>
  </tr
  <tr>
   <th 
  <td> <
  </tr>
  <tr>

 </tbody>
</table>
</stope>
</end>

#### Expected behavior 

When opening a profile, click on the close icon, the open profile should be closed and the application should not be crashed.

#### Actual behavior

 The application crashes when I click the close icon 

#### How to reproduce

* open the [application](https://github.com/quintuslabs/DatingApp/blob/master/lovedating1.0.apk)
* click on the profile info icon
* After opening the info icon click close icon
* Note the Error

* Browser/App version: 1.0
* Operating system: 6.0

#### Recording Of The Bug

![20190702_104847](https://user-images.githubusercontent.com/51118734/60485786-fac55b00-9c52-11e9-9118-bcdaf9885236.gif)

#### Logcat

<pre><code>D/AndroidRuntime(13377): Shutting down VM

E/AndroidRuntime(13377): FATAL EXCEPTION: main

E/AndroidRuntime(13377): Process: com.quintus.labs.datingapp, PID: 13377

E/AndroidRuntime(13377): java.lang.IllegalStateException: Could not find method DislikeBtn(View) in a parent or ancestor Context for android:onClick attribute defined on view class android.support.v7.widget.AppCompatImageButton with id 'dislikebtn'

E/AndroidRuntime(13377): 	at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.resolveMethod(AppCompatViewInflater.java:424)

E/AndroidRuntime(13377): 	at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:381)

E/AndroidRuntime(13377): 	at android.view.View.performClick(View.java:5076)

E/AndroidRuntime(13377): 	at android.view.View$PerformClick.run(View.java:20279)

E/AndroidRuntime(13377): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(13377): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(13377): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(13377): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(13377): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(13377): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(13377): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(13377): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

V/ApplicationPolicy( 1016): isApplicationStateBlocked userId 0 pkgname com.quintus.labs.datingapp

V/ApplicationPolicy( 1016): isApplicationStateBlocked userId 0 pkgname com.quintus.labs.datingapp
</code></pre>

**Comment by quintuslabs** [comment]
[DatingApp version 1.0 ] The application crashes when I click the close icon #2 
Issue Resolved

**Comment by quintuslabs** [comment]
[DatingApp version 1.0 ] The application crashes when I click the close icon #2
Issue Resolved
