### ISSUE TITLE
[DatingApp version 1.0 ] Text is not editing in the About option

### ISSUE THREAD

**Issue by friendsmobile** [quintuslabs/DatingApp#3]
<table class="">
 <tbody>
  <tr>
   <th scope="row">-----------------------------</a>Project Information-------------------------------------</th>
   <td>.</td>
  </tr>
  <tr>

<table class="properties">
 <tbody>
  <tr>
   <th scope="row">Project Respotry</a></th>
   <td>https://github.com/quintuslabs/DatingApp</td>
  </tr>
  <tr>
   <th scope="row">Project Name:</th>
   <td> DatingApp</a>.</td>
  </tr>
  <tr>
   <th scope="row">My Github Account</th>
   <td>  https://github.com/friendsmobile.</td>
  </tr>
  <tr>
   <th scope="row"> APK Downlod </th>
   <td> <h1><h6>https://github.com/quintuslabs/DatingApp/blob/master/lovedating1.0.apk.</td>
  </tr
  <tr>
   <th 
  <td> <
  </tr>
  <tr>

 </tbody>
</table>
</stope>
</end>

#### Expected behavior 
When I try to enter the text in the about option, the text should enter   in the option

#### Actual behavior

 Text is not editing in the About option  And the information is not being entered about in the option

#### How to reproduce

* open the application
* go to your profile
* click on the edit icon option
* enter some details in the Job title or about section 
* Note the Error

* Browser/App version: 1.0
* Operating system: 6.0

#### Recording Of The Bug
![20190703_084542](https://user-images.githubusercontent.com/51118734/60562488-a67eb180-9d0c-11e9-96f1-a8a5ed210892.gif)

**Comment by quintuslabs** [comment]
[DatingApp version 1.0 ] Text is not editing in the About option #3
Issue resoved
